# Generated by Django 3.1.4 on 2021-02-10 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_pins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Files.file'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
